Merge patch files into main script
Also adjustments to update-builds.sh

diff --git a/debian/make_dockerfile b/debian/make_dockerfile
--- a/debian/make_dockerfile
+++ b/debian/make_dockerfile
@@ -318,6 +318,7 @@ cat <<\@
 
 	ascii|beowulf|chimaera|ceres|*:devuan ) INCEXTRA='devuan-keyring' ;;
 	kali-* ) INCEXTRA='kali-archive-keyring' ;;
+	amber ) INCEXTRA='pureos-archive-keyring,gnupg' ;;
 	esac
 
 	[ "$INCEXTRA$INCLUDE" != '' ] && {
@@ -333,8 +334,6 @@ cat <<\@
 	    ${VARIANT:+--variant="$VARIANT"} \
 	    $COMP $DEBOPTIONS $EXTRA $INCEXTRA \
 	    "${RELEASE%:*}" chroot "$MIRROR" "$DEBSCRIPT"
-
-	(cd chroot-patch && tar cf - .) | (cd chroot && tar xf - )
 
 	cd /opt/chroot
 
@@ -362,6 +361,9 @@ cat <<\@
 	: "Start stage 2 for $RELEASE"
 
 	export DEBIAN_FRONTEND=noninteractive
+
+	: Output patch files.
+	sh /tmp/stage2a
 
 	: 'init sometimes uses ischroot to disable updates. (eg wheezy)'
 	if [ -x /usr/bin/ischroot ]&&[ ! -L /usr/bin/ischroot ]
@@ -453,6 +455,11 @@ cat <<\@
 	    echo >>/root/.bashrc ulimit -n 1024
 	}
 
+	[ "$RELEASE" = jessie:devuan ] && {
+	    # Workaround for Jessie apt-get is very slow issue
+	    echo >>/root/.bashrc ulimit -n 1024
+	}
+
 	# We want UTF-8, if supported.
 	{
 	    echo '[ "$(LANG=C.UTF-8 locale charmap 2>/dev/null)" = UTF-8 ]&&'
@@ -461,6 +468,108 @@ cat <<\@
 
 	: "Stage 2 complete for $RELEASE"
     } ; docker_save "Stage 2" /tmp/stage2
+
+    docker_start || {
+
+#--------------------------------------------------------------------------#
+# Patch apt and dpkg for docker
+# Note: standard used "#" for comment not "//"
+
+# ============= etc/apt/apt.conf.d/docker-clean ==============
+cat << '@' > '/etc/apt/apt.conf.d/docker-clean'
+// Since for most Docker users, package installs happen in "docker build" steps,
+// they essentially become individual layers due to the way Docker handles
+// layering, especially using CoW filesystems.  What this means for us is that
+// the caches that APT keeps end up just wasting space in those layers, making
+// our layers unnecessarily large (especially since we'll normally never use
+// these caches again and will instead just "docker build" again and make a brand
+// new image).
+
+// Ideally, these would just be invoking "apt-get clean", but in our testing,
+// that ended up being cyclic and we got stuck on APT's lock, so we get this fun
+// creation that's essentially just "apt-get clean".
+DPkg::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };
+APT::Update::Post-Invoke { "rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true"; };
+
+Dir::Cache::pkgcache "";
+Dir::Cache::srcpkgcache "";
+
+// Note that we do realize this isn't the ideal way to do this, and are always
+// open to better suggestions (https://github.com/debuerreotype/debuerreotype/issues).
+@
+# ============= etc/apt/apt.conf.d/docker-no-languages ==============
+cat << '@' > '/etc/apt/apt.conf.d/docker-no-languages'
+// In Docker, we don't often need the "Translations" files, so we're just wasting
+// time and space by downloading them, and this inhibits that.  For users that do
+// need them, it's a simple matter to delete this file and "apt-get update". :)
+
+Acquire::Languages "none";
+@
+# ============= etc/apt/apt.conf.d/docker-autoremove-suggests ==============
+cat << '@' > '/etc/apt/apt.conf.d/docker-autoremove-suggests'
+// Since Docker users are looking for the smallest possible final images, the
+// following emerges as a very common pattern:
+
+//   RUN apt-get update \
+//       && apt-get install -y <packages> \
+//       && <do some compilation work> \
+//       && apt-get purge -y --auto-remove <packages>
+
+// By default, APT will actually _keep_ packages installed via Recommends or
+// Depends if another package Suggests them, even and including if the package
+// that originally caused them to be installed is removed.  Setting this to
+// "false" ensures that APT is appropriately aggressive about removing the
+// packages it added.
+
+// https://aptitude.alioth.debian.org/doc/en/ch02s05s05.html#configApt-AutoRemove-SuggestsImportant
+Apt::AutoRemove::SuggestsImportant "false";
+@
+# ============= etc/apt/apt.conf.d/docker-gzip-indexes ==============
+cat << '@' > '/etc/apt/apt.conf.d/docker-gzip-indexes'
+// Since Docker users using "RUN apt-get update && apt-get install -y ..." in
+// their Dockerfiles don't go delete the lists files afterwards, we want them to
+// be as small as possible on-disk, so we explicitly request that Apt keep them
+// compressed on-disk too instead of decompressing them.
+
+// For comparison, an "apt-get update" layer without this on a pristine
+// "debian:wheezy" base image was "29.88 MB", where with this it was only
+// "8.273 MB".
+
+Acquire::GzipIndexes "true";
+@
+# ============= etc/dpkg/dpkg.cfg.d/docker-apt-speedup ==============
+cat << '@' > '/etc/dpkg/dpkg.cfg.d/docker-apt-speedup'
+# For most Docker users, package installs happen during "docker build", which
+# doesn't survive power loss and gets restarted clean afterwards anyhow, so
+# this minor tweak gives us a nice speedup (much nicer on spinning disks,
+# obviously).
+
+#<off> force-unsafe-io
+@
+# ============= usr/sbin/policy-rc.d ==============
+cat << '@' > '/usr/sbin/policy-rc.d'
+#!/bin/sh
+
+# For most Docker users, "apt-get install" only happens during "docker build",
+# where starting services doesn't work and often fails in humorous ways. This
+# prevents those failures by stopping the services from attempting to start.
+
+case "$1" in
+--list )
+    echo >&2 "Everything is denied by policy."
+    ;;
+--quiet|'' )
+    ;;
+* ) echo >&2 "Denied: /usr/sbin/policy-rc.d $*"
+    ;;
+esac
+exit 101 # action forbidden by policy
+@
+chmod 0755 'usr/sbin/policy-rc.d'
+
+exit 0
+
+    } ; docker_save "Stage 2a" /tmp/stage2a
 
     # shellcheck disable=SC2046,SC2086
     docker_start || {
@@ -499,13 +608,6 @@ cat <<\@
 
     docker_cmd
     docker_savefile 'Debian Potato key' /root/potato-key.gpg < potato-key.gpg
-
-    docker_cmd
-    docker_cmd '#--------------------------------------------------------------------------#'
-    docker_cmd '# Patch apt and dpkg for docker'
-    docker_cmd '# Note: standard used "#" for comment not "//"'
-    docker_cmd WORKDIR '/opt/chroot-patch'
-    base64_extras
 
     docker_cmd
     docker_cmd WORKDIR '/opt'
@@ -552,20 +654,6 @@ cat <<\@
 # Dockerfile building scriptlets
 #
 # shellcheck disable=SC1003
-base64_extras() {
-
-    tar c \
-	--owner=root --group=root \
-	--mode=og=u-w,ug-s \
-	--sort=name \
-	--mtime="$(date +%Y)-01-01 12:00:00" \
-	-f - -- etc usr |
-    {
-	echo 'RUN set -eu; _() { echo "$@";};(\'
-	gzip -n9 | base64 -w 72 | sed 's/.*/_ &;\\/'
-	echo ')|base64 -d|gzip -d|tar xf -'
-    }
-}
 
 docker_cmd() { echo "$@" ; return 0; }
 docker_start() { START_LINE=$((BASH_LINENO[0]+1)) ; }
