Updates

diff --git a/debian/Docker.d/Dockerfile.minbase b/debian/Docker.d/Dockerfile.minbase
--- a/debian/Docker.d/Dockerfile.minbase
+++ b/debian/Docker.d/Dockerfile.minbase
@@ -1,3 +1,4 @@
+#------------------------------------------------------------------------------#
 # We can use any Linux that has debootstrap as a package.
 # Ideally we want the smallest that has up to date
 # repository keys for our final target
@@ -50,43 +51,43 @@ WORKDIR /opt/chroot
 # Configure apt and dpkg for docker
 # Note: standard used "#" for comment not "//"
 RUN set -eu; _() { echo "$@";};(\
-_ H4sIAAAAAAACA+1abY/bNhLez/4VcwrQpIUte+19yTlFgbRBDwu0RZCk6JcDClqiZZ4lUiUp;\
-_ O861/73PkPLGu3k5XNH1pigHye7KpIZDDueZZ0hLX4xP7lgmkMvz8/Abcvt3+Pt0dnE+m01P;\
-_ J2dnJ5PTyWw2OaHzkyNI57ywRCfWGP+xfv+r/S8qEv4XrR9/Wv6HnCX/H9P/+J8XRi/zcvwJ;\
-_ +H82ObtI/r8n/5emWEs7Kmop9J/m/wv26/v9P52ezW75/xx/ndAk+f/OZTyml0oXkpbGUmOc;\
-_ p2fB/dQ5ad2QWlGsRSVJaaxTXTtaibaVGs+UxY1Ci07VZUbOy9YNB1DoV3JH0jmpvcI7O1rI;\
-_ wjSso1QbVXaiplrsoJ7KTpI3/AJtxW4/9ErospaOVYV+SldD6GtlEdV1Dp/QN+YnWir022Hk;\
-_ xuVEP62Ehy7lqMHWdWFKnSM8e7T0llEhipWMH9HT569oLWE3SV1S19J/sB1givM8gsPk2Wr0;\
-_ NU72Ng+pEWu0sjrT2f1MOq1lgTkLq2BhLSzW7NGBzS4s8lY+rGvSxjbhQy03caV729y1daIS;\
-_ GBfrQFuFN3j1pSijebfW/W1XGCZJ0MLigTVquSXVwHuf5wN+violDzvsh9qaru5VLniaG8Pz;\
-_ ogxQMKqkpwAA2RDjeF4EnqyXYWV6L2MBsWwyLNxC8rvFrqhVEe2WVBmPXdEVazKal/qhoxqm;\
-_ D8mZ0Cx7by07zQoLK4VXRgfN6Hu4g+LEb1qWD549X1fz+XPs2tEVmy/pv5TZhkZLGm+EHYfF;\
-_ jPBmi5XaSDf+Ii/l4oOtrbA84Pt7fZEvsAy//kredjJ7Qr89GWBS8/mPbSm8vFc7Bs+Unc+/;\
-_ 4S7zebuuQmfKsic3GpwtbrTxov9gvIyuhEdKQ/BBrd7I6Bjl9EMfgkbx1gkxinAtTWgeBj8L;\
-_ iz1XoyXEq2FsQJeF9B5b1HVVxVvGIBofrbxv3Xw8rpRfdQtkm2aM2XXSWmn8rpW3npRznXTY;\
-_ uidJ7iP/azOqha464Ie70/w/OZve5n8XF6fTlP+PlP+vdJ94hxEDOObN0iOQtQS4c/hnr5BT;\
-_ XB3g2WUx7fYw/hDxf5g1Q2pQyPYMDjGDLnbQutW1ESUnCShsInZEkNErtVA+ZmRk8W9NTz4i;\
-_ LJUmprJoCV5UnBsEEmrT1hI5LwANo5Kspe+Biw0MI1ynjC6AdJbT/PPB4GnxS6csEPG7/Qan;\
-_ TBsNMB2k+N/Hv+i8sbIxGznqYdzdTfyfzi4vbsb/dDK9PE/xf1T+f0j7Q1KvTeSDzKIZAxxz;\
-_ VuwCao1zaoEAWyoNUhAYpgukkiN1aerabPlF2UjLoSU4XEF0d4SU34DftSFm9TwQEKIXP/5A;\
-_ N8OU/h1bWD777Lqxr0FotKMv+7rEfXWr75cgJ46LDYzVqohYYLp2/dUHlLYdU3WoHIUdP4pb;\
-_ /mCAYOXXgDC5FF3th6FoCKxcFL4L7PRnriF+3tdKbm8oIGujBL3g6qcBU3ZkLCt7JtvwpJbA;\
-_ KIN1s9dl1ss+0nqsQ30QqT1cVHcBPfESe6N/4ZqIG6sqdgesKQScGNEyUrEDe4CNcYIlkPYl;\
-_ SFoEZC6RAs5mS1E7mYHXu84eVknogcLPmtYqOAijiKpCBwe6SmJhUCIEvT2+s6q3q+FJlCgT;\
-_ YhGyZ4FYf+W7Uubgm1gDJrpK6NzYigFoLPW4WE2mbnKOf/nKN/UDhidVPYXfnsJRLyI07Rfs;\
-_ qmmN9UL7ATrM5297zOfvdNnP8kmilh/B/+qNakco2eXru+Z/l+fv8j8+/0v4f1/4H09Ysvcg;\
-_ 8/vhOM/zDM/9MYayvbbAE3tGWR0wNCQXxSAX2wW4pt0KW7pAQLccoT14sULgFzJIyD78x3X2;\
-_ MXpUKnd9miBft7UqlAc0WflLx4kqglfrwxFPUBmOGZAYGLmAhr0KDGSuj1jMEnbu++zpaoQu;\
-_ ZqbcIqxyRjOFfYdfxuMgpAe/YkwMyIoEJAi4yfQ4IGMWsW6+XUn5ZpfRQjgZ0yiTaMqm/8wf;\
-_ P6bvv86wHkgOMqjryXLg2VBZ74Kmx/n0csZd8wNW+y9E7lUMXMriIcHgY/FftuvqLi+A/sD9;\
-_ zxTd0/n/kfA/+J9/5MWyuoMLoD9w/3N6MU3+vy//7wtAQJtrUXh37R2f/0xu3/9cnF+m/H8U;\
-_ eRCy2v9x8VN2NnCDG5cQnKhUsRo8QLKX4dAY5cOGa4PWbNGrRtIOdQxSJVcgvOYeCTgc5B8Q;\
-_ APTZrcyWczp0xascpbkA3UqxpooPx/lKR5BW4Cz97qRHTVeswkeWs61rldZsJCd3N4Qms9go;\
-_ 07l6xzchKGgLOeq0E0s5UubvXQR0zn6S3/+5SPf/R/O/Wyj9ifG/cP+f/H9E/7cG5dNuZIu8;\
-_ PLb/Z5eXt/nf2SR9/+M4+f8fY/a+Ww0GH6QC2a2KPwv1Z08I3AcYAdTF4jXk+vB1CglKUIQD;\
-_ gcgR+Fg2sIJ427QUquazU1p1jbFI13zf7HJ6BRoAbSjIN1KHo1H+Ngb3DkeUix2GMG3b1+pv;\
-_ h1la0xAfNTdtPOY00RZQAPkahfTp5DQdACZJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJkiRJ;\
-_ kiRJkiRJkiRJkuSvK78DrrpgNwBQAAA=;\
+_ H4sIAAAAAAACA+1abY8btxG+z/oV0zUQO4G00kn34sqGASdGigPSwLAd5EuBgNqlVqx2yQ3J;\
+_ lSw3+e99hlyddeeXokFP56Ac2He3Inc45HCeeYaU9MX45I5lArk8Pw+/Ibd/h79PZxfns9n0;\
+_ dHJ2djI5ncxmkxM6PzmCdM4LS3RijfGf6/ef2v+kIuF/0frxl+V/yFny/zH9j/95YfQyL8df;\
+_ gP9nk7OL5P978n9pirW0o6KWQv/P/H/Bfv24/6fTs9kt/5/jrxOaJP/fuYzH9FrpQtLSWGqM;\
+_ 8/QiuJ86J60bUiuKtagkKY11qmtHK9G2UuOZsrhRaNGpuszIedm64QAK/UruSDontVd4Z0cL;\
+_ WZiGdZRqo8pO1FSLHdRT2Unyhl+grdjth14JXdbSsarQT+lqCH2tLKK6zuET+s78TEuFfjuM;\
+_ 3Lic6OeV8NClHDXYui5MqXOEZ4+W3jIqRLGS8SN6/vINrSXsJqlL6lr6J7YDTHGeR3CYPFuN;\
+_ vsbJ3uYhNWKNVlZnOrufSae1LDBnYRUsrIXFmj06sNmFRd7Kh3VN2tgmfKjlJq50b5u7tk5U;\
+_ AuNiHWir8AavvhRlNO/Wur/vCsMkCVpYPLBGLbekGnjv63zAz1el5GGH/VBb09W9ygVPc2N4;\
+_ XpQBCkaV9BQAIBtiHM+LwJP1MqxM72UsIJZNhoVbSH632BW1KqLdkirjsSu6Yk1G81I/dFTD;\
+_ 9CE5E5pl761lp1lhYaXwyuigGX0Pd1Cc+E3L8sGLl+tqPn+JXTu6YvMl/Ysy29BoSeONsOOw;\
+_ mBHebLFSG+nG3+SlXHyytRWWB/x4r2/yBZbht9/I205mT+j3JwNMaj7/qS2Fl/dqx+CFsvP5;\
+_ d9xlPm/XVehMWfbkRoOzxY02XvQfjZfRlfBIaQg+qNU7GR2jnH7oQ9Ao3johRhGupQnNw+Bn;\
+_ YbHnarSEeDWMDeiykN5ji7quqnjLGETjo5X3rZuPx5Xyq26BbNOMMbtOWiuN37Xy1pNyrpMO;\
+_ W/ckyX3kf21GtdBVB/xwd5r/J2fT2/zv4uJ0mvL/kfL/le4T7zBiAMe8WXoEspYAdw7/7A1y;\
+_ iqsDPLsspt0exh8i/g+zZkgNCtmewSFm0MUOWre6NqLkJAGFTcSOCDJ6pRbKx4yMLP696clH;\
+_ hKXSxFQWLcGLinODQEJt2loi5wWgYVSStfQ9cLGBYYTrlNEFkM5ymn89GDwvfu2UBSL+sN/g;\
+_ lGmjAaaDFP/7+BedN1Y2ZiNHPYy7u4n/09nlxc34n06ml+cp/o/K/w9pf0jqtYl8kFk0Y4Bj;\
+_ zopdQK1xTi0QYEulQQoCw3SBVHKkLk1dmy2/KBtpObQEhyuI7o6Q8hvwuzbErJ4HAkL06qcf;\
+_ 6WaY0j9iC8tXX1039jUIjXb0tK9L3LNbfZ+CnDguNjBWqyJigena9bNPKG07pupQOQo7fhS3;\
+_ /MEAwcpvAWFyKbraD0PREFi5KHwX2OkvXEP8sq+V3N5QQNZGCXrF1U8DpuzIWFb2QrbhSS2B;\
+_ UQbrZq/LrNd9pPVYh/ogUnu4qO4CeuIl9kb/wjURN1ZV7A5YUwg4MaJlpGIH9gAb4wRLIO1r;\
+_ kLQIyFwiBZzNlqJ2MgOvd509rJLQA4WfNa1VcBBGEVWFDg50lcTCoEQIent8Z1XvV8OTKFEm;\
+_ xCJkzwKx/sp3pczBN7EGTHSV0LmxFQPQWOpxsZpM3eQc//KVb+oHDE+qeg6/PYejXkVo2i/Y;\
+_ VdMa64X2A3SYz9/3mM8/6LKf5ZNELT+D/9U71Y5Qssu3d83/Ls8/5H98/pfw/77wP56wZB9B;\
+_ 5o/DcZ7nGZ77Ywxle22BJ/aMsjpgaEguikEutgtwTbsVtnSBgG45QnvwYoXAL2SQkH34j+vs;\
+_ Y/SoVO76NEG+bWtVKA9osvLXjhNVBK/WhyOeoDIcMyAxMHIBDXsVGMhcH7GYJezc99nT1Qhd;\
+_ zEy5RVjljGYK+wG/jMdBSA9+xZgYkBUJSBBwk+lxQMYsYt18u5Ly3S6jhXAyplEm0ZRN/5o/;\
+_ fkx//zbDeiA5yKCuJ8uBZ0NlvQuaHufTyxl3zQ9Y7d8QuVcxcCmLhwSDz8V/2a6ru7wA+gP3;\
+_ P1N0T+f/R8L/4H/+kRfL6g4ugP7A/c/pxTT5/778vy8AAW2uReHdtXd8/nM6vZ3/zy9T/j+K;\
+_ PAhZ7b+4+Ck7G7jBjUsITlSqWA0eINnLcGiM8mHDtUFrtuhVI2mHOgapkisQXnOPBBwO8g8I;\
+_ APrsVmbLOR264lWO0lyAbqVYU8WH43ylI0grcJZ+d9KjpitW4SPL2da1Sms2kpO7G0KTWWyU;\
+_ 6Vy945uQB0/NcvmM69pCjjrtxFKOlPk/rQU6Z7/I7/9cpPv/o/nfLZT+wvhfuP9P/j+i/1uD;\
+_ 8mk3skVeHtv/s8vL2/zvbJK+/3Gc/P+XMXvfrZAXP0UFslsVfxbqz54QuE8wAqiLxWvI9eHr;\
+_ FBKUoAgHApEj8LFsYAXxtmkpVM1np7TqGmORrvm+2eX0BjQA2lCQb6QOR6P8bQzuHY4oFzsM;\
+_ Ydq2r9XfD7O0piE+am7aeMxpoi2gAPItCunTyWk6AEySJEmSJEmSJEmSJEmSJEmSJEmSJEmS;\
+_ JEmSJEmSJEmSJEmSJEmSJMmfV/4NQR5c0wBQAAA=;\
 )|base64 -d|gzip -d|tar xvf -
 
 #------------------------------------------------------------------------------#
@@ -96,25 +97,30 @@ ARG DEBIAN_FRONTEND=noninteractive
 ARG RELEASE
 ARG ARCH
 
-# init sometimes uses ischroot to disable restarting.
+# init sometimes uses ischroot to disable updates.
 RUN \
     if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \
     dpkg-divert --local --rename --add /usr/bin/ischroot;\
     ln -s /bin/true /usr/bin/ischroot; fi
 
-RUN set -x;: $RELEASE $ARCH; /debootstrap/debootstrap --second-stage
+RUN set -x;\
+ : $RELEASE $ARCH; /debootstrap/debootstrap --second-stage \
+|| dpkg --configure --pending \
+;  dpkg -l dpkg apt base-files
 
 # Clear all the manual install flags
 RUN [ ! -f /usr/bin/apt-mark ] || apt-mark auto -qq $(apt-mark showmanual) ||:
 
-# Make sure everything is installed properly
-RUN set -x;: $RELEASE $ARCH; dpkg --configure --pending
-
-# Clean up the divert I put in to stop sysvinit trying to restart itself
+# Clean up the ischroot divert.
 RUN \
     if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \
     rm -f /usr/bin/ischroot; \
     dpkg-divert --local --rename --remove /usr/bin/ischroot;fi
+
+# This option breaks some installs eg: ubuntu/maverick
+RUN dpkg --force-unsafe-io -l dpkg >/dev/null 2>&1 && \
+    sed -i -e '/^#<off> force-unsafe-io/s/#[^ ]* //' \
+        /etc/dpkg/dpkg.cfg.d/docker-apt-speedup ||:
 
 # Clean lists, cache and history.
 RUN apt-get update -qq --list-cleanup -oDir::Etc::SourceList=/dev/null
diff --git a/debian/make_dockerfile b/debian/make_dockerfile
--- a/debian/make_dockerfile
+++ b/debian/make_dockerfile
@@ -23,6 +23,7 @@ make_dockerfile() {
     [ "$RELEASE" = potato ] && ARCH=i386
     [ "$ARCH" = '' ] && ARCH=amd64
 
+    echo '#------------------------------------------------------------------------------#'
     echo '# We can use any Linux that has debootstrap as a package.'
     echo '# Ideally we want the smallest that has up to date'
     echo '# repository keys for our final target'
@@ -76,22 +77,32 @@ RUN set -e;\
     echo WORKDIR /opt
     echo '# Chroot under Docker is unreliable; use --foreign as a workaround.'
 
-    echo 'RUN set -x;DIR=/usr/share/debootstrap/scripts;\'
+    if [ "$RELEASE" = potato ]
+    then
+	echo 'RUN COMP="--components=main,contrib,non-free";\'
+	echo '    debootstrap --foreign --arch=$ARCH $COMP $DEBOPTIONS \'
+	echo '    "$RELEASE" chroot $MIRROR $DEBSCRIPT'
+	echo
 
-    echo '    if grep -q ^keyring.*ubuntu "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
-    echo '    COMP="--components=main,restricted,universe,multiverse";else \'
-    echo '    COMP="--components=main,contrib,non-free";fi;\'
+    else
+	echo 'RUN set -x;DIR=/usr/share/debootstrap/scripts;\'
 
-    echo '    if grep -q ^variants.*minbase "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
-    echo '    VARIANT="--variant=minbase";fi;\'
+	echo '    if grep -q ^keyring.*ubuntu "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
+	echo '    COMP="--components=main,restricted,universe,multiverse";else \'
+	echo '    COMP="--components=main,contrib,non-free";fi;\'
 
-    echo '    debootstrap --foreign --arch=$ARCH $VARIANT $COMP $DEBOPTIONS \'
+	echo '    if grep -q ^variants.*minbase "$DIR/${DEBSCRIPT:-$RELEASE}";then \'
+	echo '    VARIANT="--variant=minbase";fi;\'
 
-    [ "$RELEASE" = jessie ] &&
-	echo '    --exclude=systemd,systemd-sysv --include=sysvinit-core \'
+	echo '    debootstrap --foreign --arch=$ARCH $VARIANT $COMP $DEBOPTIONS \'
 
-    echo '    "$RELEASE" chroot $MIRROR $DEBSCRIPT'
-    echo
+	[ "$RELEASE" = jessie ] &&
+	    echo '    --exclude=systemd,systemd-sysv --include=sysvinit-core \'
+
+	echo '    "$RELEASE" chroot $MIRROR $DEBSCRIPT'
+	echo
+    fi
+
     echo 'WORKDIR /opt/chroot'
     echo
 
@@ -125,18 +136,20 @@ RUN set -e;\
     echo 'ARG ARCH'
     echo
 
-    echo '# init sometimes uses ischroot to disable restarting.'
-    echo 'RUN \'
-    echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
-    echo '    dpkg-divert --local --rename --add /usr/bin/ischroot;\'
-    echo '    ln -s /bin/true /usr/bin/ischroot; fi'
-    echo
-
-    echo 'RUN set -x;: $RELEASE $ARCH; /debootstrap/debootstrap --second-stage'
-    echo
+    if [ "$RELEASE" != potato ]
+    then
+	echo '# init sometimes uses ischroot to disable updates.'
+	echo 'RUN \'
+	echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
+	echo '    dpkg-divert --local --rename --add /usr/bin/ischroot;\'
+	echo '    ln -s /bin/true /usr/bin/ischroot; fi'
+	echo
+    fi
 
     if [ "$RELEASE" = jessie ]
     then
+	echo 'RUN set -x;: $RELEASE $ARCH; /debootstrap/debootstrap --second-stage'
+	echo
 	echo '# Systemd leaves a mess, unpack it again so dpkg can remove it.'
 	echo 'RUN dpkg --unpack --force-depends /var/cache/apt/archives/systemd_*.deb'
 	echo '# Sigh this breaks sysvinit ...'
@@ -147,25 +160,39 @@ RUN set -e;\
 	echo '# Oh, and fix sysvinit'
 	echo 'RUN dpkg -i /var/cache/apt/archives/sysvinit-core_*.deb'
 	echo ''
-	echo '# Remove packages that are not essential'
+	echo '# Remove packages that are not essential and check'
 	echo 'RUN apt-mark auto -qq $(apt-mark showmanual) \'
-	echo '&&  apt-get autoremove --purge -y'
+	echo '&&  apt-get autoremove --purge -y \'
+	echo '&&  apt-get update -y \'
+	echo '&&  apt-get dist-upgrade -y \'
+	echo '&&  dpkg --configure --pending'
 	echo
     else
+	echo 'RUN set -x;\'
+	echo ' : $RELEASE $ARCH; /debootstrap/debootstrap --second-stage \'
+	echo '|| dpkg --configure --pending \'
+	echo ';  dpkg -l dpkg apt base-files'
+	echo
+
 	echo '# Clear all the manual install flags'
 	echo 'RUN [ ! -f /usr/bin/apt-mark ] || apt-mark auto -qq $(apt-mark showmanual) ||:'
 	echo
     fi
 
-    echo '# Make sure everything is installed properly'
-    echo 'RUN set -x;: $RELEASE $ARCH; dpkg --configure --pending'
-    echo
+    if [ "$RELEASE" != potato ]
+    then
+	echo '# Clean up the ischroot divert.'
+	echo 'RUN \'
+	echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
+	echo '    rm -f /usr/bin/ischroot; \'
+	echo '    dpkg-divert --local --rename --remove /usr/bin/ischroot;fi'
+	echo
+    fi
 
-    echo '# Clean up the divert I put in to stop sysvinit trying to restart itself'
-    echo 'RUN \'
-    echo '    if [ -x /sbin/init -a -x /usr/bin/ischroot ] ; then \'
-    echo '    rm -f /usr/bin/ischroot; \'
-    echo '    dpkg-divert --local --rename --remove /usr/bin/ischroot;fi'
+    echo '# This option breaks some installs eg: ubuntu/maverick'
+    echo 'RUN dpkg --force-unsafe-io -l dpkg >/dev/null 2>&1 && \'
+    echo '    sed -i -e '\''/^#<off> force-unsafe-io/s/#[^ ]* //'\'' \'
+    echo '        /etc/dpkg/dpkg.cfg.d/docker-apt-speedup ||:'
     echo
 
     echo '# Clean lists, cache and history.'
